vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /upload/image/
            upload_destination: '%kernel.project_dir%/public/upload/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer